### ISSUE TITLE
Clustering method crashes

### ISSUE THREAD

**Issue by raphsilva** [raphsilva/contrastive-summarization#32]
Apparently, a problem with Numpy version. No obvious way to fix besides downgrading Numpy.

```
Traceback (most recent call last):
  File "/home/raph/Dropbox/Mestrado/Implementations/contrastive-summarization/Clustering/main.py", line 4, in <module>
    import evaluate
  File "/home/raph/Dropbox/Mestrado/Implementations/contrastive-summarization/Clustering/evaluate.py", line 3, in <module>
    import metrics
  File "/home/raph/Dropbox/Mestrado/Implementations/contrastive-summarization/Clustering/metrics.py", line 3, in <module>
    from similarity import psi, phi
  File "/home/raph/Dropbox/Mestrado/Implementations/contrastive-summarization/Clustering/similarity.py", line 1, in <module>
    from language import removeNegsAndAdjs
  File "/home/raph/Dropbox/Mestrado/Implementations/contrastive-summarization/Clustering/language.py", line 14, in <module>
    nlpnet_POSTagger = nlpnet.POSTagger()
  File "/usr/local/lib/python3.6/dist-packages/nlpnet/taggers.py", line 205, in __init__
    self._load_data()
  File "/usr/local/lib/python3.6/dist-packages/nlpnet/taggers.py", line 423, in _load_data
    self.nn = load_network(md)
  File "/usr/local/lib/python3.6/dist-packages/nlpnet/taggers.py", line 38, in load_network
    nn = net_class.load_from_file(md.paths[md.network])
  File "nlpnet/network.pyx", line 860, in nlpnet.network.Network.load_from_file (nlpnet/network.c:14631)
  File "/home/raph/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/raph/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 722, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

**Comment by raphsilva** [comment]
Fixed by updating nlpnet (v1.2.4).
https://github.com/erickrf/nlpnet/commit/60a2f14ecc834e70588fd71baf631a2bf7900b90
